### ISSUE TITLE
Unable to install Pyramid from a Wheel on Amazon Linux

### ISSUE THREAD

**Issue by shoelsch** [tgsmith61591/pyramid#16]
#### Description

I'm unable to install Pyramid from a Wheel on an Amazon Linux EC2 machine. Based on [PEP 513](https://www.python.org/dev/peps/pep-0513/#ucs-2-vs-ucs-4-builds), a `--enable-unicode` flag needs to be passed when building CPython 2.x.

#### Steps/Code to Reproduce

```
$ pip install https://pypi.python.org/packages/2a/f8/ecf7714177b509d731bcc00caf0a9712fcff9f3a2166097b417a77685ca1/pyramid_arima-0.5.1-cp27-cp27m-manylinux1_x86_64.whl#md5=01d45b14bbdf3989f1785e0c6c0ff5f0
pyramid_arima-0.5.1-cp27-cp27m-manylinux1_x86_64.whl is not a supported wheel on this platform.
```

```
$ python
Python 2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip; print(pip.pep425tags.get_supported())
[('cp27', 'cp27mu', 'manylinux1_x86_64'), ('cp27', 'cp27mu', 'linux_x86_64'), ('cp27', 'none', 'manylinux1_x86_64'), ('cp27', 'none', 'linux_x86_64'), ('py2', 'none', 'manylinux1_x86_64'), ('py2', 'none', 'linux_x86_64'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
```

#### Expected Results

I would expect both cp27m and cp27mu to be supported and uploaded to PyPI.

#### Versions

```
$ uname -a
Linux ip-192-168-49-73 4.4.23-31.54.amzn1.x86_64 #1 SMP Tue Oct 18 22:02:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$  lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	AmazonAMI
Description:	Amazon Linux AMI release 2016.09
Release:	2016.09
Codename:	n/a
```

**Comment by shoelsch** [comment]
I'm going to start to dig into this.

It's curious to me that manylinux's docker image is explicitly building two different CPython versions with both versions of the flag set: https://github.com/pypa/manylinux/blob/master/docker/build_scripts/build_utils.sh#L78-L79

I've also stumbled on this, which may or may not be related: https://github.com/travis-ci/travis-ci/issues/5107

**Comment by tgsmith61591** [comment]
Thanks for raising the flag on this. We'll certainly look into it. It does
sound like a manylinux issue at first blush...

As a workaround in the meantime, are you able to build from source by pip
installing the tar file from pypi?

**Comment by shoelsch** [comment]
Yep, I am able to, just prefer the build times of wheels for my production systems :)

**Comment by tgsmith61591** [comment]
Closing since #17 fixed this issue.
