### ISSUE TITLE
Old version args still in docstring

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pyramid#18]
#### Description

It would seem the docstring for `predict` in `ARIMA` still contains instructions RE: `include_std_err`, which was an option in older versions:

https://github.com/tgsmith61591/pyramid/blob/master/pyramid/arima/arima.py#L361

I'll call this a 'bug' even though no code functionality is impacted. It will be cleaned up in the next release.

**Comment by plelong** [comment]
Hi! 
I am trying to get confidence intervals when predicting with the ARIMA model. As the `include_conf_int` is no longer available in the new releases, do you have any idea on how I could get these values ?
Thanks for your help,

**Comment by tgsmith61591** [comment]
Hey there. Originally, pyramid supported this. Since pyramid wraps
statsmodels under the hood and ARMA models have this capability, it was
supported. However, when I introduced seasonal models into pyramid, the
ARIMA began wrapping the SARIMAX statsmodels class, which does not support
confidence intervals. I suppose if that feature were ever added to
statsmodels, that's something I could add back into pyramid.

**Comment by tgsmith61591** [comment]
Docstring was fixed in 689c003. However, I'm going to open a new issue on the backlog to re-consider confidence interval support.
