### ISSUE TITLE
approx requirement?

### ISSUE THREAD

**Issue by jonnagel** [tgsmith61591/pyramid#2]
```
conda create --name pyram_env python=3 numpy scipy scikit-learn Cython statsmodels
source activate pyram_env
python setup.py install #from this repo dir
```
> ...
> Writing /home/home/miniconda3/envs/pyram_env/lib/python3.6/site-packages/pyramid-0.3-py3.6.egg-info
> running install_clib
> customize UnixCCompiler

`python`
> Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.

`from pyramid.arima import auto_arima
`
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hom/install/pyramid/pyramid/arima/__init__.py", line 2, in <module>
>     from .approx import *
>   File "/home/hom/install/pyramid/pyramid/arima/approx.py", line 18, in <module>
>     from pyramid.arima._arima import C_Approx
> ModuleNotFoundError: No module named 'pyramid.arima._arima'
```
^d
pip install approx
python
```
> Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.

`from pyramid.arima import auto_arima`

Works

I'm on: 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

**Comment by tgsmith61591** [comment]
Did the cythonization run properly? That's the only reason I can imagine
this would occur.

**Comment by tgsmith61591** [comment]
`approx.py` is an internal submodule. If `_arima.so` is not present (i.e., if cythonizing fails), the import will not work. Can you ensure there is no cython error on setup?

**Comment by tgsmith61591** [comment]
Alternatively, try that same python import outside of the `pyramid` source dir. Chances are it's looking inside the local `arima` submodule, from which the `.so` file has moved. This should hopefully get easier once there's a pip-installable package and folks don't have to clone the package to install it...

**Comment by tgsmith61591** [comment]
Re-designed build in bd374e6. Closing for now&mdash;if this can be replicated later, will reopen.
