### ISSUE TITLE
Include confidence intervals in predictions

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pyramid#20]
#### Description

This issue is related to #18, which referenced lingering `include_std_err` args. While statsmodels' `ARMA` model supports this functionality, `SARIMAX` does not. Opening this for the backlog in case `SARIMAX` ever catches up to `ARMA` and we can re-include these parameters in `ARIMA.predict`.

**Comment by charlesdrotar** [comment]
Not certain how relevant this is but I found confidence interval support for SARIMAX [here](http://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.conf_int.html).

**Comment by typpo** [comment]
@tgsmith61591 Thanks so much for creating this project - it's great for people who are new to this area. 
 
Is there any way to derive confidence intervals from the results currently?  I'm not sure I can present the results without some sort of uncertainty.

**Comment by tgsmith61591** [comment]
Hey there @typpo this is something that I'm targeting for next release. Stay tuned. :-)

**Comment by tgsmith61591** [comment]
Just getting around to this. See 8581455 for an initial crack at it. SARIMAX doesn't make this as natural as the ARIMA class, so I had to hack it a bit to make it work.

**Comment by tgsmith61591** [comment]
This was merged into dev and will make it into the `master` branch for release 0.7. Going to leave open until the release.

**Comment by MaxMcGlinnPoole** [comment]
Very excited for this to make it into master!

**Comment by RobeeF** [comment]
Can't wait !

**Comment by RobeeF** [comment]
Thanks !

**Comment by tgsmith61591** [comment]
[Release 0.7.0](https://github.com/tgsmith61591/pyramid/releases/tag/v0.7.0) fixes this.
