### ISSUE TITLE
Multiple predictors for pyramid.arima.auto_arima()

### ISSUE THREAD

**Issue by tsoratan** [tgsmith61591/pyramid#24]
Hi, 

I am trying to get auto_arima to work with multiple predictors. 
I was using auto.arima() in R, it has xreg parameter which allow the user to put in multiple predictors for the model. 

Is this functionality available in the current version of pyramid.arima.auto_arima?

Thank you,
T

**Comment by tsoratan** [comment]
Sorry, I just looked into the code again and found that you have "exogenous" input parameter to the function.

Thank you for the documentation in the code! It is very useful.
T

**Comment by tgsmith61591** [comment]
Glad you found the doc, and glad it's helpful!
