### ISSUE TITLE
How do I use the "estimate_seasonal_differencing_term method" to test the seasonality in my data?

### ISSUE THREAD

**Issue by chen7572** [tgsmith61591/pyramid#26]
#### Description

I have a sequence of data, which is like following:
Month
2012-01-01    136.0
2012-02-01    134.0
2012-03-01     96.0
2012-04-01     79.0
2012-05-01    111.0
2012-06-01    106.0
2012-07-01    106.0
2012-08-01    119.0
2012-09-01     93.0
2012-10-01    112.0
2012-11-01    112.0
2012-12-01    108.0
2013-01-01    138.0
......

I want to test the seasonality in my data, and came across the pyramid package. 

#### Steps/Code to Reproduce

What I did is: 

```python
from pyramid.arima import seasonality

seasonality_test = pyramid.arima.seasonality.CHTest(12)
seasonality_test.estimate_seasonal_differencing_term(Data)

```

#### Actual Results
And it gave me 0, which I assume that means no 12-month seasonality. I wonder if I called the class and used the method correctly. And if there is a way to test the seasonality term, without specifying a number (12 in my case). 
Thank you!

**Comment by tgsmith61591** [comment]
So `m` is a parameter that you actually have to know. The seasonality estimator class was never intended to be a public interface; it's used by the `nsdiff` function to estimate `D`, the seasonal differencing term for ARIMAs. So the 0 you're getting back is actually the seasonal differencing term, not the seasonality.

**Comment by chen7572** [comment]
I guess I should have read the name more carefully: estimate_seasonal_differencing_term, which pretty much explains what the function does. Thank you for your response!
