### ISSUE TITLE
out_of_sample_size in auto_arima may not be implemented correctly

### ISSUE THREAD

**Issue by Barcavin** [tgsmith61591/pyramid#28]
#### Description

`out_of_sample_size ` parameter in `auto_arima` doesn't work as expected. From my understanding, the out of bag samples shouldn't be used to train the model. It is a validation dataset. But the `auto_arima` seems to implement as training on all the samples, both in and out samples.

[arima.py](https://github.com/tgsmith61591/pyramid/blob/1e4801008edd0c3dfb6b67fb0ae3ed0b2b93af72/pyramid/arima/arima.py#L239-L307)

**Comment by tgsmith61591** [comment]
I think you're right. That was an oversight. It really should be more like:

```python
        # don't allow negative, don't allow > n_samples
        cv = max(min(cv, n_samples), 0)

        # added to address #28:
        if cv:
            y = y[:-cv]
```

I'll work in a patch, and this will be addressed in the next release. Thanks for the catch!

**Comment by tgsmith61591** [comment]
Release 0.7.0 fixes this.
