### ISSUE TITLE
How to save auto arima model ?

### ISSUE THREAD

**Issue by Chakri-V-V** [tgsmith61591/pyramid#35]
Thanks in Advance!

I want to save this auto arima generated results to a pkl file, but I am finding difficulty in saving it. Can anyone help ?

**Comment by k4der2rg** [comment]
@tgsmith61591  The page doesn't exists :/ 
Any other alternatives ?

**Comment by padhariabhavesh** [comment]
For Save Model


```
  with open('model_pickle_QSC','wb') as f:
        pickle.dump(model,f)
```
 
For Load Model

```
       
    with open('model_pickle_QSC','rb') as f:
        mp = pickle.load(f)
```
