### ISSUE TITLE
How to auto get value d?

### ISSUE THREAD

**Issue by createmysoul** [tgsmith61591/pyramid#37]
hi
Could you tell me How to auto get value d?
thanks!

**Comment by tgsmith61591** [comment]
It's not a silver bullet, but here are some tips and tricks in the user guide:

https://www.alkaline-ml.com/pyramid/tips_and_tricks.html#understanding-differencing

**Comment by tgsmith61591** [comment]
It's also worth mentioning that `auto_arima` will estimate `d` if it's set to `d=None`. You can control the number of differencing terms it will try with the `max_d` parameter.
