### ISSUE TITLE
Create Updated Wheels for Python 3.6+

### ISSUE THREAD

**Issue by DeastinY** [tgsmith61591/pyramid#38]
Seems to only be available for Python 3.6 on Mac :)

**Comment by tgsmith61591** [comment]
Yeah, so this is something I mentioned at some point in #36, but the newest version will have wheels for 3.6 :)

**Comment by DeastinY** [comment]
thanks a bunch! <3

**Comment by tgsmith61591** [comment]
Handled in #42
