### ISSUE TITLE
OSError: Could not read saved model state from  Does it still exist?

### ISSUE THREAD

**Issue by sparo-jack** [tgsmith61591/pyramid#39]
/home/user/.pyramid-arima-cache/2018-10-30_23-34-59.732854-111--9223363280821728957.pmdpkl. Does it still exist?

**Comment by tgsmith61591** [comment]
Please follow the instructions in the issue template! Can you provide the following:

* Pyramid version
* Command you're running

While you're at it, please take a look at this to understand serialization in Pyramid:

https://www.alkaline-ml.com/pyramid/serialization.html

If you're in an older version of pyramid (pre 0.8.1), you might be encountering an older issue where older cached states were scrapped if re-pickling.

**Comment by tgsmith61591** [comment]
Haven't heard back on this issue, but it should have been handled in #42. If any issues persist, we can reopen...
