### ISSUE TITLE
While pip installing the package (0.8.1)  for Linux 64 bit, I encounter C exception errors 

### ISSUE THREAD

**Issue by stevejobsmyguru** [tgsmith61591/pyramid#40]
The following are error traces:

  ^
    pyramid/arima/_arima.c: In function ‘__Pyx__ExceptionSave’:
    pyramid/arima/_arima.c:26129:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         *type = tstate->exc_type;
                       ^
    pyramid/arima/_arima.c:26130:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         *value = tstate->exc_value;
                        ^
    pyramid/arima/_arima.c:26131:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         *tb = tstate->exc_traceback;
                     ^
    pyramid/arima/_arima.c: In function ‘__Pyx__ExceptionReset’:
    pyramid/arima/_arima.c:26138:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    pyramid/arima/_arima.c:26139:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    pyramid/arima/_arima.c:26140:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    pyramid/arima/_arima.c:26141:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = type;
               ^
    pyramid/arima/_arima.c:26142:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = value;
               ^
    pyramid/arima/_arima.c:26143:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = tb;
               ^
    pyramid/arima/_arima.c: In function ‘__Pyx__GetException’:
    pyramid/arima/_arima.c:26198:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    pyramid/arima/_arima.c:26199:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    pyramid/arima/_arima.c:26200:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    pyramid/arima/_arima.c:26201:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = local_type;
               ^
    pyramid/arima/_arima.c:26202:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = local_value;
               ^
    pyramid/arima/_arima.c:26203:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = local_tb;
               ^
    pyramid/arima/_arima.c: In function ‘__Pyx__ExceptionSwap’:
    pyramid/arima/_arima.c:27811:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    pyramid/arima/_arima.c:27812:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    pyramid/arima/_arima.c:27813:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    pyramid/arima/_arima.c:27814:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = *type;
               ^
    pyramid/arima/_arima.c:27815:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = *value;
               ^
    pyramid/arima/_arima.c:27816:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = *tb;
               ^
    cc1: warning: pyramid/arima/_arima_fast_helpers.h: not a directory
    In file included from /root/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                     from /root/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /root/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pyramid/arima/_arima.c:308:
    /root/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    pyramid/arima/_arima.c: In function ‘__Pyx__ExceptionSave’:
    pyramid/arima/_arima.c:26129:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         *type = tstate->exc_type;
                       ^
    pyramid/arima/_arima.c:26130:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         *value = tstate->exc_value;
                        ^
    pyramid/arima/_arima.c:26131:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         *tb = tstate->exc_traceback;
                     ^
    pyramid/arima/_arima.c: In function ‘__Pyx__ExceptionReset’:
    pyramid/arima/_arima.c:26138:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    pyramid/arima/_arima.c:26139:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    pyramid/arima/_arima.c:26140:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    pyramid/arima/_arima.c:26141:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = type;
               ^
    pyramid/arima/_arima.c:26142:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = value;
               ^
    pyramid/arima/_arima.c:26143:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = tb;
               ^
    pyramid/arima/_arima.c: In function ‘__Pyx__GetException’:
    pyramid/arima/_arima.c:26198:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    pyramid/arima/_arima.c:26199:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    pyramid/arima/_arima.c:26200:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    pyramid/arima/_arima.c:26201:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = local_type;
               ^
    pyramid/arima/_arima.c:26202:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = local_value;
               ^
    pyramid/arima/_arima.c:26203:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = local_tb;
               ^
    pyramid/arima/_arima.c: In function ‘__Pyx__ExceptionSwap’:
    pyramid/arima/_arima.c:27811:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    pyramid/arima/_arima.c:27812:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    pyramid/arima/_arima.c:27813:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    pyramid/arima/_arima.c:27814:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = *type;
               ^
    pyramid/arima/_arima.c:27815:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = *value;
               ^
    pyramid/arima/_arima.c:27816:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = *tb;
               ^
    error: Command "gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DSCIPY_MKL_H -DHAVE_CBLAS -I/root/anaconda3/lib/python3.7/site-packages/numpy/core/include -Ipyramid/arima/_arima_fast_helpers.h -I/usr/local/include -I/usr/include -I/root/anaconda3/include -I/root/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/root/anaconda3/include/python3.7m -c pyramid/arima/_arima.c -o build/temp.linux-x86_64-3.7/pyramid/arima/_arima.o -MMD -MF build/temp.linux-x86_64-3.7/pyramid/arima/_arima.o.d" failed with exit status 1
    
    ----------------------------------------
Command "/root/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l8uexday/pyramid-arima/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9s7bpwcq/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-l8uexday/pyramid-arima/

**Comment by tgsmith61591** [comment]
Looks like you're on Python 3.7. Try with 3.6

**Comment by stevejobsmyguru** [comment]
I downloaded differ tar.gz file from https://github.com/tgsmith61591/pyramid/archive/v0.8.1.tar.gz.

This above link is provided under the Project Links section of https://pypi.org/project/pyramid-arima/.


I used this tar.gz file and It was successful installation.

I also verified tat the tar.gz file given in download file section 9https://pypi.org/project/pyramid-arima/#files) is wrong file. it was the one failed. 

pls. publish right files in the pypi folder location.

**Comment by tgsmith61591** [comment]
I'm not sure I understand. The Tar file in the git artifacts is the same as the one on Pypi (the deployment is automated via CI/CD). I'm fairly certain whatever broke/worked in the end was not a result of the tar itself, though 3.7 compatibility is a known issue, so I still think that's the culprit.

**Comment by tgsmith61591** [comment]
Ok so upon more thought, I'm a bit off ^

The tar on Pypi is a source dist of the package itself (*just* the package; not the project) generated by `python setup.py sdist`. The archive on git is literally the whole project tarred up, and that's not something that would ever go out on Pypi. But as your stack trace reflects, Python 3.7 is a bit wonky with the package, as we've seen in other issues (see some of the later comments in #27 especially)

**Comment by stevejobsmyguru** [comment]
Thx for ur reply. I will try with Python 3.6 instead and keep you posted.

Initially I built freshly with latest Python 3.7 thru Anaconda set up for Ubuntu and CentOS.

No Prob. Going forward, I will actively contribute to this Git because I use Auto Arima extensively
