### ISSUE TITLE
Pip Install of Pyramid-Arima in windows (64 bit) is failing while compiling C Program 

### ISSUE THREAD

**Issue by stevejobsmyguru** [tgsmith61591/pyramid#41]
I am using Python 3.6.5 in windows machine

The following is error trace:

    copying pyramid\arima\arima.py -> build\lib.win-amd64-3.6\pyramid\arima
    copying pyramid\arima\auto.py -> build\lib.win-amd64-3.6\pyramid\arima
    copying pyramid\arima\seasonality.py -> build\lib.win-amd64-3.6\pyramid\arim
a
    copying pyramid\arima\setup.py -> build\lib.win-amd64-3.6\pyramid\arima
    copying pyramid\arima\stationarity.py -> build\lib.win-amd64-3.6\pyramid\ari
ma
    copying pyramid\arima\utils.py -> build\lib.win-amd64-3.6\pyramid\arima
    copying pyramid\arima\warnings.py -> build\lib.win-amd64-3.6\pyramid\arima
    copying pyramid\arima\__init__.py -> build\lib.win-amd64-3.6\pyramid\arima
    creating build\lib.win-amd64-3.6\pyramid\arima\tests
    copying pyramid\arima\tests\test_approx.py -> build\lib.win-amd64-3.6\pyrami
d\arima\tests
    copying pyramid\arima\tests\test_arima.py -> build\lib.win-amd64-3.6\pyramid
\arima\tests
    copying pyramid\arima\tests\test_c_arima.py -> build\lib.win-amd64-3.6\pyram
id\arima\tests
    copying pyramid\arima\tests\test_stationarity.py -> build\lib.win-amd64-3.6\
pyramid\arima\tests
    copying pyramid\arima\tests\__init__.py -> build\lib.win-amd64-3.6\pyramid\a
rima\tests
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying f
rom distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'pyramid.__check_build._check_build' extension
    compiling C sources
    creating build\temp.win-amd64-3.6\Release\pyramid
    creating build\temp.win-amd64-3.6\Release\pyramid\__check_build
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC
\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Pro
gramData\Anaconda3\lib\site-packages\numpy\core\include -ID:\ProgramData\Anacond
a3\lib\site-packages\numpy\core\include -ID:\ProgramData\Anaconda3\include -ID:\
ProgramData\Anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio\
2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" /Tcpyramid\__check_build\_che
ck_build.c /Fobuild\temp.win-amd64-3.6\Release\pyramid\__check_build\_check_buil
d.obj
    _check_build.c
    d:\programdata\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot o
pen include file: 'io.h': No such file or directory
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildToo
ls\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDE
BUG /MD -ID:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include -ID:\Pro
gramData\Anaconda3\lib\site-packages\numpy\core\include -ID:\ProgramData\Anacond
a3\include -ID:\ProgramData\Anaconda3\include -I"C:\Program Files (x86)\Microsof
t Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" /Tcpyramid\__
check_build\_check_build.c /Fobuild\temp.win-amd64-3.6\Release\pyramid\__check_b
uild\_check_build.obj" failed with exit status 2

    ----------------------------------------
Command "D:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;
__file__='D:\\TEMP\\8\\pip-req-build-0gbcdk1r\\setup.py';f=getattr(tokenize, 'op
en', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(
code, __file__, 'exec'))" install --record D:\TEMP\8\pip-record-u4fe8b_r\install
-record.txt --single-version-externally-managed --compile" failed with error cod

**Comment by tgsmith61591** [comment]
So this one *is* my problem, and it's a known issue. See #38. Next release will have pre-built 3.6 wheels that should (hopefully) solve this

**Comment by tgsmith61591** [comment]
If you don't want to wait for the wheels to be built for version 0.9.0, see [this SO answer](https://stackoverflow.com/a/50210015/3015734). You need to install VS build tools

**Comment by tgsmith61591** [comment]
Closing since A) #42 pushed out wheels for 3.6 on Windows and B) this was actually an artifact of having to build from source (with a deficient environment) rather than a pre-compiled wheel.
