### ISSUE TITLE
Circle CI addition

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pyramid#5]
@charlesdrotar can you help out with Circle CI? I'd like to use the same (and/or more) envs that are in the `.travis.yml`.

**Comment by charlesdrotar** [comment]
I'm sorry I don't know how to do that ;). Just kidding. Do you want slack/email integration as well? I can set it up to only do so on failure and fix.

**Comment by charlesdrotar** [comment]
On a side note Travis CI also has Slack Integration which is pretty slick as well. All you need to do is enable it within Slack. It may be worth incorporating both of the hooks whenever Circle CI gets incorporated.

**Comment by tgsmith61591** [comment]
We already have appveyor for Windows builds, and Travis for Linux/Mac builds. I don't think we need Circle in addition (especially since Mac builds there cost 💸💸💸). Closing.
