### ISSUE TITLE
Add requirements.txt to installation steps.

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/pyramid#6]
So it appears that using a fresh environment will cause errors in the installation process given that the requirements.txt is not mentioned within the installation section of the `README.md`. Although the preceding section has the basic requirements there, I feel this section should be as streamlined as possible to facilitate users who are not just conda users. 

I think this is :+1: for virtual envs.

**Comment by charlesdrotar** [comment]
This is a temporary solution until a wheel is built and served in pypi.

**Comment by tgsmith61591** [comment]
This is at least handled in `develop` branch, though it has not been pulled into `master` yet:

```python
extra_setuptools_args = dict(
        zip_safe=False,
        include_package_data=True,
        package_data={'pyramid': ['*']},
        distclass=BinaryDistribution,
        install_requires=REQUIREMENTS,  # RIGHT HERE
)
```
