### ISSUE TITLE
Serve pyramid on pypi

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/pyramid#7]
We need to streamline the installation,  so naturally the move to serving pyramid on pypi makes sense to reduce the need for assumptions in the installation process about the underlying environment. 

Conceivably this could be served as a single wheel as [h2o](https://pypi.python.org/pypi/pandas/0.20.2) does with multiple versions of python, operating systems, and architectures supported or possibly as series of wheels as [numpy](https://pypi.python.org/pypi/numpy/1.13.0), [scikit-learn](https://pypi.python.org/pypi/scikit-learn/0.18.2) or [pandas](https://pypi.python.org/pypi/pandas/0.20.2) does with separate OS versions, python versions, and architectures getting their own wheels. 

Not sure what the most elegant solution is. Maybe trying to serve the following 6 major wheels makes the most sense:

- os: MAC 64-bit architecture
  - **[in pypitest]** python: 2.7 
  - **[in pypitest]** python: 3.5 
  - **[in pypitest]** python: 2.6 
- os: Linux 64-bit architecture
  - python: 2.7 
  - python: 3.5 
  - python: 2.6 

## \<OS\> \<os_version\> using Python \<major_version\>.\<minor_version\> 
- [ ] **1.)** serve the package on the pypi test server, then:
- [ ] **2.)** test install from pypi test server 
  - [ ] **a.** with requirements already installed:
    - [ ] anaconda
    - [ ] virtualenv
  - [ ] **b.** with requirements not already installed:
    - [ ] anaconda
    - [ ] virtualenv
  - [ ] **c.** with conflicting versions:
    - [ ] anaconda
    - [ ] virtualenv
- [ ] **3.)** serve the package publicly

**Comment by charlesdrotar** [comment]
There are classifieres within `setup.py` that are invalid. You will have to restrict yourself to the following valid ones:

https://pypi.python.org/pypi?:action=browse

The invalid ones are:
1. **Intended Audience :: Scikit-learn users**
2. **Intended Audience :: R users**
3. **Topic :: Machine Learning**

**Comment by charlesdrotar** [comment]
0. Create a `~/.pypirc`

```bash
# These are the contents of the ~/.pypirc

[distutils]
index-servers =
  pypi
  pypitest

# Need to set this up still
[pypi]
repository=https://pypi.python.org/pypi
username=<NEED TO CREATE>
password=<NEED TO CREATE>

[pypitest]
repository=https://test.pypi.org/legacy/
username=<ASK ME FOR IT>
password=<ASK ME FOR IT>
```

To upload to pypi test server, for each environment run (from the base directory):

1. `pip install -r requirements.txt`
2. `pip install twine`
3. `rm -rf dist/`
4. `python setup.py bdist_wheel`
5. `twine upload dist/* -r pypitest`

**To upload to pypi "production" server, for each environment run the same commands except replace `pypitest` with `pypi`**.

**Comment by charlesdrotar** [comment]
In order to test across multiple OSs (linux and MAC) we would need to either have a linux box or setup some VMs to run in different environments with similar virtual environments in them in addition to our macs. This would allow us to build the wheels across OSs. I think for now we would only need to create Linux and Mac:

## MAC INSTALLATIONS : 
### PYTHON 2.7
```bash
(pyramid) Charless-MBP:pyramid_fork charlesdrotar$ pip install -i https://testpypi.python.org/pypi py-arima
Collecting py-arima
  Downloading https://testpypi.python.org/packages/ab/b0/eae37fed0f7b9bcdcfebdd1a373fccc0e492c40bf203c73cc6163838c24b/py_arima-0.5.dev0-cp27-cp27m-macosx_10_7_x86_64.whl (128kB)
    100% |████████████████████████████████| 133kB 83kB/s
Installing collected packages: py-arima
Successfully installed py-arima-0.5.dev0
```

### PYTHON 3.5
```bash
(pyramid_35) Charless-MBP:pyramid_fork charlesdrotar$ pip install -i https://testpypi.python.org/pypi py-arima
Collecting py-arima
  Downloading https://testpypi.python.org/packages/0b/3d/6910b62f31ac9cd4ec683573e62cb2e721bef43cc1107a412963e9245b5e/py_arima-0.5.dev0-cp35-cp35m-macosx_10_7_x86_64.whl (121kB)
    100% |████████████████████████████████| 122kB 1.1MB/s
Installing collected packages: py-arima
Successfully installed py-arima-0.5.dev0
```

### PYTHON 3.6
```bash
(pyramid_36) Charless-MBP:pyramid_fork charlesdrotar$ pip install -i https://testpypi.python.org/pypi py-arima
Collecting py-arima
  Downloading https://testpypi.python.org/packages/37/4c/81b9b39dfebe7fb18c3c5ed74769a43a0bdfd44401b9ddfeb4a5786f1eea/py_arima-0.5.dev0-cp36-cp36m-macosx_10_7_x86_64.whl (121kB)
    100% |████████████████████████████████| 122kB 64kB/s
Installing collected packages: py-arima
Successfully installed py-arima-0.5.dev0
```

**Comment by charlesdrotar** [comment]
One major consideration is that if you screw up in uploading a wheel and you don't like what is in there and you need to release another one - ❗️**YOU CAN NOT USE THE SAME VERSION NUMBER**❗️

**Comment by tgsmith61591** [comment]
1. Would you suggest, then, that we decrement minimum numpy version to 1.9.3?
2. Let's keep cython around in `requirements.txt` unless:
3. Does `bdist_wheel` build the project and push the compiled `.so` files as well? Or will there be un-built C code on the other end of the pypi installation?

**Comment by tgsmith61591** [comment]
Ultimately, we need some script that manages build (sphinx and C), tag & release from `master`. But that will be the final stage in this whole saga.

**Comment by charlesdrotar** [comment]
@tgsmith61591 in response to your numbered questions:

1. Honestly that is an executive decision based on what your package requires. What happens is that the pypi server finds packages within itself that satisfy the baseline requirements you set forth in `install_requires`. Given that this is most likely just a factor of the test server only having that version I would do what you think makes the most sense since when the `.whl` is deployed to the production server it will have all versions of numpy that are collocated there available.
2.  (.. and 3) I will have to do a little sleuthing to validate that part.

**Comment by charlesdrotar** [comment]
On aforementioned points 2 and 3 we should be including Cython and numpy to ensure that building of code goes off without a hitch.

**Comment by tgsmith61591** [comment]
To address your earlier remark, the following wheels should be built:

- os: MAC 64-bit architecture
  - **[in pypitest]** python: 2.7 
  - **[in pypitest]** python: 3.5 
  - **[in pypitest]** python: 2.6 
- os: Linux 64-bit architecture
  - python: 2.7 
  - python: 3.5 
  - python: 2.6
        python: 3.5
        python: 2.6

**Comment by tgsmith61591** [comment]
Done and tested in 52f2f70a9b05fcbbc314d5db7bf488a1f88edfce. Can be installed via pip like so:

```bash
$ pip install pyramid-arima
```
